# Generated by Django 3.1 on 2020-08-17 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crt_date', models.DateField(auto_created=True)),
                ('name', models.CharField(default='Quest', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Block', max_length=50)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road_map.mainquest')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crt_date', models.DateField(auto_created=True)),
                ('name', models.CharField(default='Event', max_length=50)),
                ('main_img', models.ImageField(upload_to='')),
                ('upd_date', models.DateField(auto_now=True)),
                ('desc', models.TextField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road_map.mainblock')),
                ('category', models.ManyToManyField(to='road_map.Category')),
                ('status', models.ManyToManyField(to='road_map.Status')),
            ],
        ),
    ]
