# Generated by Django 3.1 on 2020-08-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='crt_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
