# Generated by Django 3.1 on 2020-08-17 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('road_map', '0002_auto_20200817_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='category',
        ),
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='road_map.category'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='events',
            name='status',
        ),
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='road_map.status'),
            preserve_default=False,
        ),
    ]
