# Generated by Django 3.1 on 2020-08-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_map', '0003_auto_20200817_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='category',
        ),
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.ManyToManyField(to='road_map.Category'),
        ),
        migrations.RemoveField(
            model_name='events',
            name='status',
        ),
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.ManyToManyField(to='road_map.Status'),
        ),
    ]
