# Generated by Django 3.1 on 2020-08-17 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('road_map', '0005_auto_20200817_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='road_map.category'),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='road_map.status'),
        ),
    ]
