# Generated by Django 3.1 on 2020-08-17 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('road_map', '0007_auto_20200817_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='road_map.mainblock'),
        ),
    ]
